### ISSUE TITLE
Framework survey

### ISSUE THREAD

**Issue by Polpetta** [Augugrumi/thesis-tasks#36]
Create a 10-15 line explanation about the quality of the following categories for the Openbaton, OpenStack, and Kubernetes frameworks:
- [x] Community (activity, responsiveness, overall quality)
- [x] Software lifecycle and development pace (too fast, too slow, too different from the other frameworks, etc...)
- [x] Bugs
  - [x] Software (functional)
  - [x] Issues about scalability, memory consumpion, time-to-deploy (non-functional)
- [x] Platform integration feasebility

**Comment by mzanella** [comment]
Done
